### ISSUE TITLE
Needs more MSG

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#3] opened 2013-02-11 03:15 UTC
I would like to show more MSG in duel CUI.

**Comment by mayah** [comment] 2015-03-18 11:48
Now that MSG is divided into multiple lines with comma in gui viewer. Does anyone want to do in cui?

**Comment by peria** [comment] 2015-03-18 14:18
I want a CUI environment, but is there any change in CUI?
If CUI environment will have an issue only in showing messages, I mean, it will run and show correct fields, I will work for the message issue.

**Comment by peria** [comment] 2015-05-26 10:40
Close as a duplicate of #34.

**Closed by peria** 2015-05-26 10:40 UTC
Labels: Infra
